#spring
spring:
  #bd
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_HOST_PORT}/${DB_NAME}
  #flyway
  flyway:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_HOST_PORT}/${DB_NAME}
